# Generated by Django 4.1.3 on 2022-11-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
