# Generated by Django 4.1.4 on 2022-12-07 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_etf_instance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_first_line', models.CharField(max_length=255)),
                ('address_second_line', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(max_length=189)),
                ('address_postcode', models.CharField(max_length=8)),
                ('ni', models.CharField(max_length=9)),
                ('passport_path', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('card_last_4', models.CharField(max_length=255)),
                ('validated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Validated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.account')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.transaction_type')),
            ],
        ),
    ]
