# Generated by Django 4.1.2 on 2022-12-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_transaction_type_user_details_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf_instance',
            name='price_on_create',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
